; Evolution types
EV_LEVEL   EQU 1
EV_ITEM    EQU 2
EV_TRADE   EQU 3
EV_MAP     EQU 4
EV_MOVE    EQU 5
EV_RAND    EQU 6
EV_TYROGUE EQU 7

;For Tyrogue
ATK_HIGHER EQU 1
BOTH_EQUAL EQU 2
DEF_HIGHER EQU 3
