OVERWORLD    EQU 0
REDS_HOUSE_1 EQU 1
MART         EQU 2
FOREST       EQU 3
REDS_HOUSE_2 EQU 4
OAK_TS       EQU 5
POKECENTER   EQU 6
GYM          EQU 7
HOUSE        EQU 8
FOREST_GATE  EQU 9  ; unused
MUSEUM       EQU 10
UNDERGROUND  EQU 11 ; unused
GATE         EQU 12
SHIP         EQU 13
SHIP_PORT    EQU 14
CEMETERY     EQU 15
INTERIOR     EQU 16
CAVERN       EQU 17
LOBBY        EQU 18
MANSION      EQU 19
LAB          EQU 20
CLUB         EQU 21
FACILITY     EQU 22
PLATEAU      EQU 23
SAFARI       EQU 24
FERRY        EQU 25
ICE_CAVERN   EQU 26
