; sometimes it's necessary to add $C8 to these values
const_value = 1

	const YOUNGSTER     ; $01
	const BUG_CATCHER   ; $02
	const LASS          ; $03
	const SAILOR        ; $04
	const JR__TRAINER_M ; $05
	const JR__TRAINER_F ; $06
	const POKEMANIAC    ; $07
	const SUPER_NERD    ; $08
	const HIKER         ; $09
	const BIKER         ; $0A
	const BURGLAR       ; $0B
	const ENGINEER      ; $0C
	const COUPLE        ; $0D
	const FISHER        ; $0E
	const SWIMMER       ; $0F
	const CUE_BALL      ; $10
	const GAMBLER       ; $11
	const BEAUTY        ; $12
	const PSYCHIC_TR    ; $13
	const ROCKER        ; $14
	const JUGGLER       ; $15
	const TAMER         ; $16
	const BIRD_KEEPER   ; $17
	const BLACKBELT     ; $18
	const SONY1         ; $19
	const SWIMMER_F     ; $1A
	const ROCKET_F      ; $1B
	const SCIENTIST     ; $1C
	const GIOVANNI      ; $1D
	const ROCKET        ; $1E
	const COOLTRAINER_M ; $1F
	const COOLTRAINER_F ; $20
	const BRUNO         ; $21
	const BROCK         ; $22
	const MISTY         ; $23
	const LT__SURGE     ; $24
	const ERIKA         ; $25
	const KOGA          ; $26
	const BLAINE        ; $27
	const SABRINA       ; $28
	const GENTLEMAN     ; $29
	const SONY2         ; $2A
	const SONY3         ; $2B
	const LORELEI       ; $2C
	const CHANNELER     ; $2D
	const AGATHA        ; $2E
	const LANCE         ; $2F
	const HEX_MANIAC    ; $30
	const PKMN_TRAINER  ; $31

; Entries below this are only sprites, not actual classes
	const TRACEY        ; $32
	const EXECUTIVE_F   ; $33
	const EXECUTIVE_M   ; $34
	const ROCKER_F      ; $35
	const JESSIE_JAMES  ; $36
	const COSPLAY_GIRL  ; $37
	const JANINE        ; $38
	const PLAYER_M      ; $39
	const PLAYER_F      ; $3A
	const PROF_OAK      ; $3B
	const PI_TRAINER    ; $3C
	const FLANNERY      ; $3D
	const JESSIE        ; $3E
	const JAMES         ; $3F
	const GIOVANNI_2    ; $40
