	tilepal 0, GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  WATER,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   BROWN,  BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   BROWN,  GRAY,   GRAY,   BROWN,  GRAY,   BROWN,  GRAY,   BROWN,  BROWN,  GRAY,   GRAY
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY
