	db GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  RED,    RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  RED,    RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN
	db BROWN,  BROWN,  RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db GRAY,   GRAY,   RED,    GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  GREEN,  GREEN,  BLUE,   BROWN
	db GRAY,   GRAY,   RED,    GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY
