	tilepal 0, GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  RED,    RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  RED,    RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN
	tilepal 0, BROWN,  BROWN,  RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, GRAY,   GRAY,   RED,    GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  GREEN,  GREEN,  WATER,   BROWN
	tilepal 0, GRAY,   GRAY,   RED,    GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY
