	tilepal 0, GRAY,   RED,    BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  YELLOW, GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, GRAY,   GRAY,   BROWN,  BROWN,  WATER,   GREEN,  GREEN,  BROWN,  YELLOW, GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, RED,    RED,    RED,    BROWN,  YELLOW, YELLOW, BROWN,  BROWN,  GREEN,  GREEN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN
	tilepal 0, RED,    RED,    RED,    GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  RED,    BROWN,  BROWN,  RED,    GRAY,   BROWN,  GRAY,   BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY
