	db GRAY,   RED,    BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  YELLOW, GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db GRAY,   GRAY,   BROWN,  BROWN,  BLUE,   GREEN,  GREEN,  BROWN,  YELLOW, GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db RED,    RED,    RED,    BROWN,  YELLOW, YELLOW, BROWN,  BROWN,  GREEN,  GREEN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN
	db RED,    RED,    RED,    GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  RED,    BROWN,  BROWN,  RED,    GRAY,   BROWN,  GRAY,   BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY
