	tilepal 0, GREEN,  YELLOW, BROWN,  BROWN,  ROOF,   ROOF,   ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  BROWN,  BROWN
	tilepal 0, GRAY,   GRAY,   BROWN,  BROWN,  WATER,   ROOF,   ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, GREEN,  BROWN,  BROWN,  ROOF,   ROOF,   ROOF,   ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, GREEN,  BROWN,  BROWN,  GRAY,   GREEN,  BROWN,  BROWN,  RED,    BROWN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GREEN
	tilepal 0, GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN
