	db BROWN,  GREEN,  GRAY,   GRAY,   RED,    GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db GRAY,   GRAY,   GRAY,   GRAY,   RED,    GREEN,  GREEN,  BROWN,  BROWN,  ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  ROOF,   ROOF,   GRAY,   GRAY
	db BROWN,  ROOF,   BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  RED,    RED,    GRAY,   ROOF,   BROWN,  ROOF,   ROOF,   GRAY,   GRAY
	db GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  GRAY,   BROWN,  GRAY,   BROWN,  BROWN,  GRAY,   GRAY
	db GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  RED,    GRAY
