	db BROWN,  GRAY,   GRAY,   GRAY,   RED,    GRAY,   BLUE,   BLUE,   GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  BROWN,  BROWN
	db GRAY,   GRAY,   GRAY,   GRAY,   RED,    GRAY,   BLUE,   BLUE,   BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN
	db GRAY,   GRAY,   BLUE,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
