	db GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  BROWN,  BROWN,  BLUE,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   BROWN,  BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   BROWN,  GRAY,   GRAY,   BROWN,  GRAY,   BROWN,  GRAY,   BROWN,  BROWN,  GRAY,   GRAY
	db GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY
