	tilepal 0, GRAY,   GREEN,  GREEN,  GRAY,   GRAY,   BROWN,  BROWN,  GREEN,  GREEN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  GREEN
	tilepal 0, GREEN,  BROWN,  BROWN,  RED,    RED,    BROWN,  BROWN,  GREEN,  GREEN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY
	tilepal 0, GRAY,   BROWN,  BROWN,  RED,    RED,    GRAY,   GRAY,   GREEN,  GREEN,  GREEN,  GREEN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	tilepal 0, GRAY,   RED,    RED,    RED,    GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  GREEN,  GREEN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN
	tilepal 0, BROWN,  RED,    RED,    RED,    RED,    GRAY,   RED,    RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, GREEN,  BROWN,  BROWN,  RED,    RED,    RED,    RED,    GRAY,   BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  GRAY
