	db GRAY,   GREEN,  GREEN,  GRAY,   GRAY,   BROWN,  BROWN,  GREEN,  GREEN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  GREEN
	db GREEN,  BROWN,  BROWN,  RED,    RED,    BROWN,  BROWN,  GREEN,  GREEN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY
	db GRAY,   BROWN,  BROWN,  RED,    RED,    GRAY,   GRAY,   GREEN,  GREEN,  GREEN,  GREEN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	db GRAY,   RED,    RED,    RED,    GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  GREEN,  GREEN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN
	db BROWN,  RED,    RED,    RED,    RED,    GRAY,   RED,    RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db GREEN,  BROWN,  BROWN,  RED,    RED,    RED,    RED,    GRAY,   BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  GRAY
