	tilepal 0, GRAY,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  GRAY,   GRAY
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  ROOF,   ROOF,   GRAY,   GRAY
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   ROOF,   GRAY,   RED,    BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  RED,    RED,    GRAY,   RED,    GRAY,   GRAY,   BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  RED,    RED,    ROOF,   GRAY
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   ROOF,   ROOF,   BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY
