	tilepal 0, GRAY,   RED,    RED,    RED,    RED,    BROWN,  RED,    ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   ROOF
	tilepal 0, GRAY,   BROWN,  RED,    RED,    RED,    BROWN,  RED,    ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   ROOF
	tilepal 0, YELLOW, RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   ROOF,   GRAY,   BROWN,  BROWN,  GREEN,  GREEN,  RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   ROOF,   GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  BROWN,  RED,    BROWN,  BROWN,  GRAY,   GRAY
