	db GRAY,   RED,    RED,    RED,    RED,    BROWN,  RED,    ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   ROOF
	db GRAY,   BROWN,  RED,    RED,    RED,    BROWN,  RED,    ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   ROOF
	db YELLOW, RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	db BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	db GRAY,   GRAY,   GRAY,   GRAY,   ROOF,   GRAY,   BROWN,  BROWN,  GREEN,  GREEN,  RED,    BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db GRAY,   GRAY,   GRAY,   GRAY,   ROOF,   GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  BROWN,  RED,    BROWN,  BROWN,  GRAY,   GRAY
