	tilepal 0, GRAY,   BROWN,  GRAY,   GRAY,   RED,    ROOF,   BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY
	tilepal 0, GRAY,   ROOF,   GRAY,   GRAY,   RED,    YELLOW, BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY
	tilepal 0, ROOF,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  YELLOW, BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	tilepal 0, BROWN,  GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  GREEN,  GREEN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
