	db GRAY,   BROWN,  GRAY,   GRAY,   RED,    ROOF,   BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY
	db GRAY,   ROOF,   GRAY,   GRAY,   RED,    YELLOW, BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY
	db ROOF,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  YELLOW, BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	db BROWN,  GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY
	db BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  GREEN,  GREEN,  GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
