	tilepal 0, BROWN,  RED,    GRAY,   GRAY,   RED,    GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   RED,    GREEN,  GREEN,  BROWN,  BROWN,  ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  ROOF,   ROOF,   ROOF,   ROOF
	tilepal 0, ROOF,   ROOF,   BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  RED,    RED,    GRAY,   ROOF,   BROWN,  ROOF,   ROOF,   GRAY,   GRAY
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   ROOF,   ROOF,   BROWN,  GRAY,   BROWN,  GRAY,   BROWN,  BROWN,  GRAY,   GRAY
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  RED,    GRAY
