	db ROOF,   GRAY,   BROWN,  RED,    GRAY,   GRAY,   RED,    BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  GRAY
	db ROOF,   GRAY,   BROWN,  BROWN,  BLUE,   GRAY,   RED,    BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  GRAY
	db GRAY,   GRAY,   BROWN,  BROWN,  ROOF,   ROOF,   ROOF,   ROOF,   GRAY,   BROWN,  BROWN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN
	db GRAY,   GRAY,   BROWN,  BROWN,  ROOF,   ROOF,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  RED,    RED,    ROOF,   RED
	db GREEN,  GREEN,  ROOF,   ROOF,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN
	db GREEN,  GREEN,  ROOF,   ROOF,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   BROWN,  BROWN
