	tilepal 0, ROOF,   GRAY,   BROWN,  RED,    GRAY,   GRAY,   RED,    BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  GRAY
	tilepal 0, ROOF,   GRAY,   BROWN,  BROWN,  WATER,   GRAY,   RED,    BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  GRAY
	tilepal 0, GRAY,   GRAY,   BROWN,  BROWN,  ROOF,   ROOF,   ROOF,   ROOF,   GRAY,   BROWN,  BROWN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN
	tilepal 0, GRAY,   GRAY,   BROWN,  BROWN,  ROOF,   ROOF,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  RED,    RED,    ROOF,   RED
	tilepal 0, GREEN,  GREEN,  ROOF,   ROOF,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN
	tilepal 0, GREEN,  GREEN,  ROOF,   ROOF,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   BROWN,  BROWN
