	db GRAY,   BROWN,  BROWN,  RED,    BROWN,  ROOF,   ROOF,   ROOF,   ROOF,   ROOF,   YELLOW, YELLOW, YELLOW, GRAY,   BROWN,  GRAY
	db GRAY,   BROWN,  ROOF,   BROWN,  BLUE,   ROOF,   ROOF,   ROOF,   ROOF,   ROOF,   GRAY,   BROWN,  BROWN,  GREEN,  BROWN,  GRAY
	db GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  ROOF,   ROOF,   BROWN,  ROOF,   ROOF,   GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GRAY
	db GREEN,  GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   GRAY,   GRAY,   GRAY,   BROWN,  GREEN,  GREEN,  GRAY
	db GREEN,  GREEN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  GRAY,   BROWN,  ROOF,   ROOF,   GRAY,   GRAY
	db GREEN,  GREEN,  GREEN,  ROOF,   BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  ROOF,   BROWN,  ROOF,   ROOF,   GRAY,   GRAY
