	tilepal 0, GRAY,   BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  GREEN,  GREEN,  GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN,  BROWN
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  WATER,   BROWN,  BROWN,  GREEN,  GREEN,  GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN,  BROWN
	tilepal 0, GRAY,   GRAY,   BROWN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  GRAY,   GRAY
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   ROOF,   ROOF
	tilepal 0, ROOF,   ROOF,   ROOF,   ROOF,   ROOF,   GREEN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
