	db GRAY,   BROWN,  BROWN,  GRAY,   GRAY,   BROWN,  BROWN,  GREEN,  GREEN,  GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  BROWN,  BROWN,  BLUE,   BROWN,  BROWN,  GREEN,  GREEN,  GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN,  BROWN
	db GRAY,   GRAY,   BROWN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  GREEN,  GRAY,   GRAY
	db BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  ROOF,   ROOF,   ROOF
	db ROOF,   ROOF,   ROOF,   ROOF,   ROOF,   GREEN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	db GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
