	db GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN,  GRAY,   GRAY,   ROOF,   GRAY,   ROOF,   GRAY,   RED,    GRAY,   ROOF,   ROOF
	db ROOF,   GRAY,   RED,    RED,    BROWN,  BROWN,  GRAY,   RED,    BROWN,  BROWN,  GRAY,   GRAY,   RED,    RED,    ROOF,   ROOF
	db GREEN,  GREEN,  BROWN,  BROWN,  RED,    YELLOW, RED,    RED,    BROWN,  ROOF,   RED,    RED,    ROOF,   ROOF,   ROOF,   ROOF
	db GREEN,  GREEN,  BROWN,  BROWN,  RED,    YELLOW, GRAY,   RED,    ROOF,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   ROOF,   ROOF
	db GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   ROOF,   ROOF,   YELLOW, YELLOW
	db GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY
