	tilepal 0, BROWN,  GRAY,   GRAY,   GRAY,   RED,    GRAY,   WATER,   WATER,   GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   RED,    GRAY,   WATER,   WATER,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY
	tilepal 0, GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY
	tilepal 0, BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	tilepal 0, GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  GRAY,   GRAY,   GRAY
