	db BROWN,  GRAY,   GRAY,   GRAY,   RED,    GRAY,   BLUE,   BLUE,   GREEN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY
	db GRAY,   GRAY,   GRAY,   GRAY,   RED,    GRAY,   BLUE,   BLUE,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY
	db GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY
	db BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY
	db GRAY,   GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	db GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  GRAY,   GRAY,   GRAY
