	db GREEN,  YELLOW, BROWN,  BROWN,  ROOF,   ROOF,   ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GREEN,  BROWN,  BROWN
	db GRAY,   GRAY,   BROWN,  BROWN,  BLUE,   ROOF,   ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db GREEN,  BROWN,  BROWN,  ROOF,   ROOF,   ROOF,   ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db GREEN,  BROWN,  BROWN,  GRAY,   GREEN,  BROWN,  BROWN,  RED,    BROWN,  GREEN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN
	db BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GREEN
	db GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN,  GREEN
