	tilepal 0, GRAY,   GREEN,  WATER,   WATER,   WATER,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY,   WATER,   WATER,   WATER
	tilepal 0, WATER,   WATER,   BROWN,  BROWN,  WATER,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN
	tilepal 0, WATER,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   WATER,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN
	tilepal 0, WATER,   WATER,   BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY
	tilepal 0, WATER,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   BROWN,  BROWN
	tilepal 0, GREEN,  WATER,   GRAY,   GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  BROWN,  BROWN,  GRAY,   WATER,   GRAY,   GRAY,   GRAY,   GRAY
