	db GRAY,   GRAY,   ROOF,   ROOF,   YELLOW, GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN,  GRAY,   BROWN,  GRAY,   RED,    RED
	db GRAY,   GRAY,   ROOF,   ROOF,   BLUE,   GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN,  GRAY,   BROWN,  RED,    RED,    RED
	db ROOF,   ROOF,   GRAY,   YELLOW, RED,    GRAY,   GRAY,   BROWN,  BROWN,  ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  GREEN,  GREEN
	db ROOF,   ROOF,   GRAY,   GRAY,   RED,    RED,    BROWN,  BROWN,  BROWN,  ROOF,   ROOF,   BROWN,  BROWN,  BROWN,  GREEN,  GREEN
	db BROWN,  BROWN,  RED,    RED,    BROWN,  BROWN,  GRAY,   GRAY,   RED,    RED,    YELLOW, GRAY,   GRAY,   GRAY,   GRAY,   GRAY
	db BROWN,  BROWN,  GRAY,   GRAY,   RED,    RED,    GRAY,   GRAY,   RED,    RED,    GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY
