	db GRAY,   GREEN,  BLUE,   BLUE,   BLUE,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY,   BLUE,   BLUE,   BLUE
	db BLUE,   BLUE,   BROWN,  BROWN,  BLUE,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN
	db BLUE,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BLUE,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN
	db BLUE,   BLUE,   BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  GRAY,   GRAY,   GRAY
	db BLUE,   GRAY,   BROWN,  BROWN,  GRAY,   GRAY,   GRAY,   GRAY,   BROWN,  BROWN,  BROWN,  BROWN,  BROWN,  GRAY,   BROWN,  BROWN
	db GREEN,  BLUE,   GRAY,   GRAY,   GRAY,   GRAY,   GREEN,  GREEN,  BROWN,  BROWN,  GRAY,   BLUE,   GRAY,   GRAY,   GRAY,   GRAY
