ItemNames:
	db "Master Ball@"
	db "Ultra Ball@"
	db "Great Ball@"
	db "Poké Ball@"
	db "Town Map@"
	db "Bicycle@"
	db "?????@"
	db "Safari Ball@"
	db "Pokédex@"
	db "Moon Stone@"
	db "Antidote@"
	db "Burn Heal@"
	db "Ice Heal@"
	db "Awakening@"
	db "ParalyzeHeal@"
	db "Full Restore@"
	db "Max Potion@"
	db "Hyper Potion@"
	db "Super Potion@"
	db "Potion@"
	db "Bait@"
	db "Rock@"
	db "Old Sea Map@"
	db "MysticTicket@"
	db "Eon Ticket@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Escape Rope@"
	db "Repel@"
	db "Old Amber@"
	db "Fire Stone@"
	db "ThunderStone@"
	db "Water Stone@"
	db "HP Up@"
	db "Protein@"
	db "Iron@"
	db "Carbos@"
	db "Calcium@"
	db "Rare Candy@"
	db "Dome Fossil@"
	db "Helix Fossil@"
	db "Secret Key@"
	db "Sun Stone@"
	db "Bike Voucher@"
	db "X Accuracy@"
	db "Leaf Stone@"
	db "Card Key@"
	db "Nugget@"
	db "Thief Ball@"
	db "Poké Doll@"
	db "Full Heal@"
	db "Revive@"
	db "Max Revive@"
	db "Guard Spec.@"
	db "Super Repel@"
	db "Max Repel@"
	db "Dire Hit@"
	db "Coin@"
	db "Fresh Water@"
	db "Soda Pop@"
	db "Lemonade@"
	db "S.S. Ticket@"
	db "Gold Teeth@"
	db "X Attack@"
	db "X Defend@"
	db "X Speed@"
	db "X Special@"
	db "Coin Case@"
	db "Oak's Parcel@"
	db "Item Finder@"
	db "Silph Scope@"
	db "Poké Flute@"
	db "Lift Key@"
	db "Exp. Share@"
	db "Old Rod@"
	db "Good Rod@"
	db "Super Rod@"
	db "PP Up@"
	db "Ether@"
	db "Max Ether@"
	db "Elixir@"
	db "Max Elixir@"
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
	db "Oran Berry@"
	db "Sitrus Berry@"
	db "Leppa Berry@"
	db "Pecha Berry@"
	db "Rawst Berry@"
	db "Aspear Berry@"
	db "Chesto Berry@"
	db "Cheri Berry@"
	db "Lum Berry@"
	db "Acai Berry@"
	db "Go Home@"
