MoveNames::
	db "Pound@"
	db "Karate Chop@"
	db "Double Slap@"
	db "Comet Punch@"
	db "Mega Punch@"
	db "Pay Day@"
	db "Fire Punch@"
	db "Ice Punch@"
	db "ThunderPunch@"
	db "Scratch@"
	db "Vice Grip@"
	db "Guillotine@"
	db "Razor Wind@"
	db "Swords Dance@"
	db "Cut@"
	db "Gust@"
	db "Wing Attack@"
	db "Whirlwind@"
	db "Fly@"
	db "Bind@"
	db "Slam@"
	db "Vine Whip@"
	db "Stomp@"
	db "Double Kick@"
	db "Mega Kick@"
	db "Jump Kick@"
	db "Rolling Kick@"
	db "Sand Attack@"
	db "Headbutt@"
	db "Horn Attack@"
	db "Fury Attack@"
	db "Horn Drill@"
	db "Tackle@"
	db "Body Slam@"
	db "Wrap@"
	db "Take Down@"
	db "Thrash@"
	db "Double-Edge@"
	db "Tail Whip@"
	db "Poison Sting@"
	db "Twineedle@"
	db "Pin Missile@"
	db "Leer@"
	db "Bite@"
	db "Growl@"
	db "Roar@"
	db "Sing@"
	db "Supersonic@"
	db "Sonic Boom@"
	db "Disable@"
	db "Acid@"
	db "Ember@"
	db "Flamethrower@"
	db "Mist@"
	db "Water Gun@"
	db "Hydro Pump@"
	db "Surf@"
	db "Ice Beam@"
	db "Blizzard@"
	db "Psybeam@"
	db "Bubble Beam@"
	db "Aurora Beam@"
	db "Hyper Beam@"
	db "Peck@"
	db "Drill Peck@"
	db "Submission@"
	db "Low Kick@"
	db "Counter@"
	db "Seismic Toss@"
	db "Strength@"
	db "Absorb@"
	db "Mega Drain@"
	db "Leech Seed@"
	db "Growth@"
	db "Razor Leaf@"
	db "Solar Beam@"
	db "PoisonPowder@"
	db "Stun Spore@"
	db "Sleep Powder@"
	db "Petal Dance@"
	db "String Shot@"
	db "Dragon Rage@"
	db "Fire Spin@"
	db "Thundershock@"
	db "Thunderbolt@"
	db "Thunder Wave@"
	db "Thunder@"
	db "Rock Throw@"
	db "Earthquake@"
	db "Fissure@"
	db "Dig@"
	db "Toxic@"
	db "Confusion@"
	db "Psychic@"
	db "Hypnosis@"
	db "Meditate@"
	db "Agility@"
	db "Quick Attack@"
	db "Rage@"
	db "Teleport@"
	db "Night Shade@"
	db "Mimic@"
	db "Screech@"
	db "Double Team@"
	db "Recover@"
	db "Harden@"
	db "Minimize@"
	db "Smokescreen@"
	db "Confuse Ray@"
	db "Withdraw@"
	db "Defense Curl@"
	db "Barrier@"
	db "Light Screen@"
	db "Haze@"
	db "Reflect@"
	db "Focus Energy@"
	db "Bide@"
	db "Metronome@"
	db "Mirror Move@"
	db "SelfDestruct@"
	db "Egg Bomb@"
	db "Lick@"
	db "Smog@"
	db "Sludge@"
	db "Bone Club@"
	db "Fire Blast@"
	db "Waterfall@"
	db "Clamp@"
	db "Swift@"
	db "Skull Bash@"
	db "Spike Cannon@"
	db "Constrict@"
	db "Amnesia@"
	db "Kinesis@"
	db "Softboiled@"
	db "Hi Jump Kick@"
	db "Glare@"
	db "Dream Eater@"
	db "Poison Gas@"
	db "Barrage@"
	db "Leech Life@"
	db "Lovely Kiss@"
	db "Sky Attack@"
	db "Transform@"
	db "Bubble@"
	db "Dizzy Punch@"
	db "Spore@"
	db "Flash@"
	db "Psywave@"
	db "Splash@"
	db "Acid Armor@"
	db "Crabhammer@"
	db "Explosion@"
	db "Fury Swipes@"
	db "Bonemerang@"
	db "Rest@"
	db "Rock Slide@"
	db "Hyper Fang@"
	db "Hone Claws@"
	db "Conversion@"
	db "Tri Attack@"
	db "Super Fang@"
	db "Slash@"
	db "Substitute@"
	db "Struggle@"
	db "Metal Claw@"
	db "Bullet Punch@"
	db "Flash Cannon@"
	db "Iron Tail@"
	db "Meteor Mash@"
	db "Crunch@"
	db "Dark Pulse@"
	db "Feint Attack@"
	db "Night Slash@"
	db "Moonblast@"
	db "DrainingKiss@"
	db "Disarm Voice@"
	db "DazzlinGleam@"
	db "Draco Meteor@"
	db "DragonBreath@"
	db "Dragon Claw@"
	db "Dragon Pulse@"
	db "Twister@"
	db "Outrage@"
	db "Shadow Claw@"
	db "Steel Wing@"
	db "Iron Defense@"
	db "Air Slash@"
	db "Fire Fang@"
	db "Flare Blitz@"
	db "Blast Burn@"
	db "Ice Fang@"
	db "Thunder Fang@"
	db "Water Pulse@"
	db "Aqua Tail@"
	db "Hydro Cannon@"
	db "Frenzy Plant@"
	db "Sucker Punch@"
	db "Shadow Ball@"
	db "Flame Wheel@"
	db "HealingLight@"
	db "Hex@"
	db "Shadow Punch@"
	db "Aerial Ace@"
	db "Acrobatics@"
	db "Air Cutter@"
	db "Icy Wind@"
	db "Ice Shard@"
	db "Sheer Cold@"
	db "Electro Ball@"
	db "Nuzzle@"
	db "Discharge@"
	db "Volt Tackle@"
	db "Muddy Water@"
	db "Whirlpool@"
	db "Giga Drain@"
	db "PetalBlizard@"
	db "Leaf Blade@"
	db "Wood Hammer@"
	db "Poison Jab@"
	db "Gunk Shot@"
	db "Poison Fang@"
	db "Sludge Wave@"
	db "Silver Wind@"
	db "Bug Buzz@"
	db "Megahorn@"
	db "X-Scissor@"
	db "Signal Beam@"
	db "Earth Power@"
	db "Mud-Slap@"
	db "Mud Bomb@"
	db "Extrasensory@"
	db "Zen Headbutt@"
	db "Psycho Cut@"
	db "Hyper Voice@"
	db "ExtremeSpeed@"
	db "Giga Impact@"
	db "Power Gem@"
	db "Rock Blast@"
	db "Rock Polish@"
	db "Rock Tomb@"
	db "DynamicPunch@"
	db "Storm Throw@"
	db "Cross Chop@"
	db "Low Sweep@"
	db "Hurricane@"
	db "BabyDollEyes@"
	db "Bone Rush@"
	db "Aeroblast@"
	db "AncientPower@"
	db "Dive@"
	db "Luster Purge@"
	db "Mind Blast@"

