MoveNames:: ; b0000 (2c:4000)
	db "POUND@"
	db "KARATE CHOP@"
	db "DOUBLESLAP@"
	db "COMET PUNCH@"
	db "MEGA PUNCH@"
	db "PAY DAY@"
	db "FIRE PUNCH@"
	db "ICE PUNCH@"
	db "THUNDERPUNCH@"
	db "SCRATCH@"
	db "VICEGRIP@"
	db "GUILLOTINE@"
	db "RAZOR WIND@"
	db "SWORDS DANCE@"
	db "CUT@"
	db "GUST@"
	db "WING ATTACK@"
	db "WHIRLWIND@"
	db "FLY@"
	db "BIND@"
	db "SLAM@"
	db "VINE WHIP@"
	db "STOMP@"
	db "DOUBLE KICK@"
	db "MEGA KICK@"
	db "JUMP KICK@"
	db "ROLLING KICK@"
	db "SAND-ATTACK@"
	db "HEADBUTT@"
	db "HORN ATTACK@"
	db "FURY ATTACK@"
	db "HORN DRILL@"
	db "TACKLE@"
	db "BODY SLAM@"
	db "WRAP@"
	db "TAKE DOWN@"
	db "THRASH@"
	db "DOUBLE-EDGE@"
	db "TAIL WHIP@"
	db "POISON STING@"
	db "TWINEEDLE@"
	db "PIN MISSILE@"
	db "LEER@"
	db "BITE@"
	db "GROWL@"
	db "ROAR@"
	db "SING@"
	db "SUPERSONIC@"
	db "SONICBOOM@"
	db "DISABLE@"
	db "ACID@"
	db "EMBER@"
	db "FLAMETHROWER@"
	db "MIST@"
	db "WATER GUN@"
	db "HYDRO PUMP@"
	db "SURF@"
	db "ICE BEAM@"
	db "BLIZZARD@"
	db "PSYBEAM@"
	db "BUBBLEBEAM@"
	db "AURORA BEAM@"
	db "HYPER BEAM@"
	db "PECK@"
	db "DRILL PECK@"
	db "SUBMISSION@"
	db "LOW KICK@"
	db "COUNTER@"
	db "SEISMIC TOSS@"
	db "STRENGTH@"
	db "ABSORB@"
	db "MEGA DRAIN@"
	db "LEECH SEED@"
	db "GROWTH@"
	db "RAZOR LEAF@"
	db "SOLARBEAM@"
	db "POISONPOWDER@"
	db "STUN SPORE@"
	db "SLEEP POWDER@"
	db "PETAL DANCE@"
	db "STRING SHOT@"
	db "DRAGON RAGE@"
	db "FIRE SPIN@"
	db "THUNDERSHOCK@"
	db "THUNDERBOLT@"
	db "THUNDER WAVE@"
	db "THUNDER@"
	db "ROCK THROW@"
	db "EARTHQUAKE@"
	db "FISSURE@"
	db "DIG@"
	db "TOXIC@"
	db "CONFUSION@"
	db "PSYCHIC@"
	db "HYPNOSIS@"
	db "MEDITATE@"
	db "AGILITY@"
	db "QUICK ATTACK@"
	db "RAGE@"
	db "TELEPORT@"
	db "NIGHT SHADE@"
	db "MIMIC@"
	db "SCREECH@"
	db "DOUBLE TEAM@"
	db "RECOVER@"
	db "HARDEN@"
	db "MINIMIZE@"
	db "SMOKESCREEN@"
	db "CONFUSE RAY@"
	db "WITHDRAW@"
	db "DEFENSE CURL@"
	db "BARRIER@"
	db "LIGHT SCREEN@"
	db "HAZE@"
	db "REFLECT@"
	db "FOCUS ENERGY@"
	db "BIDE@"
	db "METRONOME@"
	db "MIRROR MOVE@"
	db "SELFDESTRUCT@"
	db "EGG BOMB@"
	db "LICK@"
	db "SMOG@"
	db "SLUDGE@"
	db "BONE CLUB@"
	db "FIRE BLAST@"
	db "WATERFALL@"
	db "CLAMP@"
	db "SWIFT@"
	db "SKULL BASH@"
	db "SPIKE CANNON@"
	db "CONSTRICT@"
	db "AMNESIA@"
	db "KINESIS@"
	db "SOFTBOILED@"
	db "HI JUMP KICK@"
	db "GLARE@"
	db "DREAM EATER@"
	db "POISON GAS@"
	db "BARRAGE@"
	db "LEECH LIFE@"
	db "LOVELY KISS@"
	db "SKY ATTACK@"
	db "TRANSFORM@"
	db "BUBBLE@"
	db "DIZZY PUNCH@"
	db "SPORE@"
	db "FLASH@"
	db "PSYWAVE@"
	db "SPLASH@"
	db "ACID ARMOR@"
	db "CRABHAMMER@"
	db "EXPLOSION@"
	db "FURY SWIPES@"
	db "BONEMERANG@"
	db "REST@"
	db "ROCK SLIDE@"
	db "HYPER FANG@"
	db "SHARPEN@"
	db "CONVERSION@"
	db "TRI ATTACK@"
	db "SUPER FANG@"
	db "SLASH@"
	db "SUBSTITUTE@"
	db "STRUGGLE@"
	db "METAL CLAW@"
	db "BULLET PUNCH@"
	db "FLASH CANNON@"
	db "IRON TAIL@"
	db "METEOR MASH@"
	db "CRUNCH@"
	db "DARK PULSE@"
	db "FEINT ATTACK@"
	db "NIGHT SLASH@"
	db "MOONBLAST@"
	db "DRAININGKISS@"
	db "DISARM VOICE@"
	db "DAZZLINGLEAM@"
	db "DRACO METEOR@"
	db "DRAGONBREATH@"
	db "DRAGON CLAW@"
	db "DRAGON PULSE@"
	db "TWISTER@"
	db "OUTRAGE@"
	db "SHADOW CLAW@"
	db "STEEL WING@"
	db "IRON DEFENSE@"
	db "AIR SLASH@"
	db "FIRE FANG@"
	db "FLARE BLITZ@"
	db "BLAST BURN@"
	db "ICE FANG@"
	db "THUNDER FANG@"
	db "WATER PULSE@"
	db "AQUA TAIL@"
	db "HYDRO CANNON@"
	db "FRENZY PLANT@"
	db "SUCKER PUNCH@"
	db "SHADOW BALL@"
	db "FLAME WHEEL@"
	db "MOONLIGHT@"
	db "HEX@"
	db "SHADOW PUNCH@"
	db "AERIAL ACE@"
	db "ACROBATICS@"
	db "AIR CUTTER@"
	db "ICY WIND@"
	db "ICE SHARD@"
	db "SHEER COLD@"
	db "ELECTRO BALL@"
	db "NUZZLE@"
	db "DISCHARGE@"
	db "VOLT TACKLE@"
	db "MUDDY WATER@"
	db "WHIRLPOOL@"
	db "GIGA DRAIN@"
	db "PETALBLIZARD@"
	db "LEAF BLADE@"
	db "WOOD HAMMER@"
	db "POISON JAB@"
	db "GUNK SHOT@"
	db "POISON FANG@"
	db "SLUDGE WAVE@"
	db "SILVER WIND@"
	db "BUG BUZZ@"
	db "MEGAHORN@"
	db "X-SCISSOR@"
	db "SIGNAL BEAM@"
	db "EARTH POWER@"
	db "MUD-SLAP@"
	db "MUD BOMB@"
	db "EXTRASENSORY@"
	db "ZEN HEADBUTT@"
	db "PSYCHO CUT@"
	db "HYPER VOICE@"
	db "EXTREMESPEED@"
	db "GIGA IMPACT@"
	db "POWER GEM@"
	db "ROCK BLAST@"
	db "ROCK POLISH@"
	db "ROCK TOMB@"
	db "DYNAMICPUNCH@"
	db "CIRCLE THROW@"
	db "CROSS CHOP@"
	db "LOW SWEEP@"
	db "HURRICANE@"
	db "BABYDOLLEYES@"
	db "BONE RUSH@"
	db "AEROBLAST@"
	db "ANCIENTPOWER@"
	db "DIVE@"
    db "LUSTER PURGE@"
    db "PSYSTRIKE@"

