TrainerNames:
	db "Youngster@"
	db "Bug Catcher@"
	db "Lass@"
	db "Sailor@"
	db "Camper@"
	db "Picnicker@"
	db "Poké Maniac@"
	db "Super Nerd@"
	db "Hiker@"
	db "Biker@"
	db "Burglar@"
	db "Engineer@"
	db "Couple@"
	db "Fisherman@"
	db "Swimmer@"
	db "Roughneck@"
	db "Gambler@"
	db "Beauty@"
	db "Psychic@"
	db "Guitarist@"
	db "Juggler@"
	db "Tamer@"
	db "Bird Keeper@"
	db "Black Belt@"
	db "Rival@"
	db "Swimmer@"
	db "Rocket@"
	db "Scientist@"
	db "Boss@"
	db "Rocket@"
	db "Ace Trainer@"
	db "Ace Trainer@"
	db "Elite Four@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Gentleman@"
	db "Rival@"
	db "Champion@"
	db "Elite Four@"
	db "Channeler@"
	db "Elite Four@"
	db "Elite Four@"
	db "Hex Maniac@"
	db "Trainer@"
